### ISSUE TITLE
Problem installing extension

### ISSUE THREAD

**Issue by Ifitrains** [tarleb/parse-latex#2]
I operate on `quarto 1.2.` and downloaded the most recent quarto version from [here](https://quarto.org/docs/download/). I can install other [extensions](https://www.google.com/search?client=firefox-b-d&q=quarto+extensions). I get the following error when trying to run `quarto install extension tarleb/parse-latex`:

> [>] Downloading
> parse-latex-main/parse-latex.lua: Can't create '\\\\?\\C:\\Users\\xxx\\AppData\\Local\\Temp\\quarto-session7f3e7ca9\\71bfff44\\2878763e\\archive\\parse-latex-main\\parse-latex.lua'
> tar.exe: Error exit delayed from previous errors.
> [>] Unzipping
> ERROR: Failed to unzip extension.
> parse-latex-main/parse-latex.lua: Can't create '\\\\?\\C:\\Users\\xxx\\AppData\\Local\\Temp\\quarto-session7f3e7ca9\\71bfff44\\2878763e\\archive\\parse-latex-main\\parse-latex.lua'
> tar.exe: Error exit delayed from previous errors.

**Comment by tarleb** [comment]
That's curious, I tried with the latest Quarto version and couldn't reproduce it. @cscheid, do you have an idea what's going on?

**Comment by cscheid** [comment]
I can't reproduce this either; @lfitrains, can you please ensure you're running 1.2.269?

```$ quarto --version
1.2.269
```

**Comment by Ifitrains** [comment]
yes, I run on version 1.2.269. It also works for me on the Rstudio Servers, but not on my local RStudio. The part that confuses me is that other extensions, for instance https://github.com/quarto-ext/fontawesome, work without a problem.

**Comment by cscheid** [comment]
That points to a difference between Windows and Linux (assuming your RStudio servers are running on linux?)

**Comment by tarleb** [comment]
Could you try to install again? I've bumped the version to 1.0.0 (up from 0.0.1). I've seen some version-related issues before, so this might help.

**Comment by Ifitrains** [comment]
This did not help, but I figured out the problem. It is related to a 00LOCK file in the lib directory. So I think we can close that issue. Sorry for the late reply!
