### ISSUE TITLE
Harmonize Hyperlinks

### ISSUE THREAD

**Issue by Ifitrains** [tarleb/parse-latex#4]
Is there perhaps a way to reach the same style of hyperlinks using your filter, i.e. get the same output using `\ref` as using quarto's @?

MWE:
```
---
filters:
  - parse-latex
---

\section{First Section}     \label{first section}

Reference to \ref{first section}.


# Second Section {#sec-second-section}

Reference to @sec-second-section.
```

![image](https://user-images.githubusercontent.com/43036806/210350546-519b9123-86f8-4408-886b-fe6a8384ed75.png)

**Comment by Ifitrains** [comment]
I'm unaware if that is possible adding this to the lua filter, but we could deal with this using regex, e.g.

```
"\\section{first section}    \\label{first paragraph}" |>
  # section
  stringr::str_replace_all("\\\\section\\{ *([^}]+) *\\} *", "# \\1 ") |>
  # label
  stringr::str_replace_all("\\\\label\\{ *(.+) *\\}", "\\{#sec-\\1\\}") |>  
  # introducing the sec tag
  stringr::str_replace_all("[[:space:]]+(?=[^{#sec]*\\})", "-")
```

*Result:*
`"# first section {#sec-first-paragraph}"`

**Comment by tarleb** [comment]
Handling of references is very different from the aims of this filter and would require a completely new filter. Sorry.
